services:
  flask:
    build: app
    container_name: flask
    ports:
      - 5000:5000
      - 8000:8000
    volumes:
      - ./:/var/www
      - .:/app
    command: gunicorn --workers 4 --threads 2 --timeout 30 --bind 0.0.0.0:8000 'app:create_app()'
    environment:
      FLASK_DEBUG: 1
      FLASK_SERVER_PORT: 5000
    networks:
      dockernet:
        aliases:
          - flask-app

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
      - 443:443
    networks:
      - dockernet
    depends_on:
      - flask

volumes:
  db_data:

networks:
  dockernet: